export enum MarketSentimentErrorCode {
  MARKET_SENTIMENT_PROVIDER_RATE_LIMITED = 'MARKET_SENTIMENT_PROVIDER_RATE_LIMITED',
  MARKET_SENTIMENT_PROVIDER_TIMEOUT = 'MARKET_SENTIMENT_PROVIDER_TIMEOUT',
  MARKET_SENTIMENT_PROVIDER_UNAVAILABLE = 'MARKET_SENTIMENT_PROVIDER_UNAVAILABLE',
  MARKET_SENTIMENT_PROVIDER_BAD_REQUEST = 'MARKET_SENTIMENT_PROVIDER_BAD_REQUEST',
  MARKET_SENTIMENT_PROVIDER_INVALID_RESPONSE = 'MARKET_SENTIMENT_PROVIDER_INVALID_RESPONSE'
}
