export enum PortfolioErrorCode {
  PORTFOLIO_NOT_FOUND = 'PORTFOLIO_NOT_FOUND',
  PORTFOLIO_ASSET_NOT_FOUND = 'PORTFOLIO_ASSET_NOT_FOUND',
  HOLDING_NOT_FOUND = 'HOLDING_NOT_FOUND',
  HOLDING_ALREADY_EXISTS = 'HOLDING_ALREADY_EXISTS',
  HOLDING_EMPTY_UPDATE = 'HOLDING_EMPTY_UPDATE'
}
