export enum PortfolioErrorCode {
  PORTFOLIO_NOT_FOUND = 'PORTFOLIO_NOT_FOUND',
  PORTFOLIO_ASSET_NOT_FOUND = 'PORTFOLIO_ASSET_NOT_FOUND',
  PORTFOLIO_EMPTY_UPDATE = 'PORTFOLIO_EMPTY_UPDATE',
  HOLDING_NOT_FOUND = 'HOLDING_NOT_FOUND',
  HOLDING_ALREADY_EXISTS = 'HOLDING_ALREADY_EXISTS',
  HOLDING_EMPTY_UPDATE = 'HOLDING_EMPTY_UPDATE',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_EMPTY_UPDATE = 'TRANSACTION_EMPTY_UPDATE',
  TRANSACTION_TYPE_NOT_SUPPORTED = 'TRANSACTION_TYPE_NOT_SUPPORTED',
  TRANSACTION_PRICE_REQUIRED = 'TRANSACTION_PRICE_REQUIRED',
  INVALID_CURSOR = 'INVALID_CURSOR',
  INSUFFICIENT_HOLDINGS = 'INSUFFICIENT_HOLDINGS',
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  TRANSFER_DESTINATION_REQUIRED = 'TRANSFER_DESTINATION_REQUIRED',
  TRANSFER_EXCHANGE_NAME_REQUIRED = 'TRANSFER_EXCHANGE_NAME_REQUIRED',
  TRANSFER_WALLET_NOT_FOUND = 'TRANSFER_WALLET_NOT_FOUND'
}
