export enum ErrorDomain {
  AUTH = 'AUTH',
  AUTHORIZATION = 'AUTHORIZATION',
  ASSETS = 'ASSETS',
  PORTFOLIO = 'PORTFOLIO',
  WALLET = 'WALLET',
  COIN_TRACKER = 'COIN_TRACKER',
  MARKET_OVERVIEW = 'MARKET_OVERVIEW',
  MARKET_SENTIMENT = 'MARKET_SENTIMENT',
  USER = 'USER',
  SESSION = 'SESSION',
  TOKEN = 'TOKEN',
  SYSTEM = 'SYSTEM',
  HTTP = 'HTTP',
  VALIDATION = 'VALIDATION',
  SECURITY = 'SECURITY'
}
