import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as argon2 from 'argon2';
import * as bcrypt from 'bcrypt';
import { PinoLogger } from 'nestjs-pino';
import { HashingProvider } from './hashing.provider';

/**
 * Argon2id password hashing with backward-compatible bcrypt support.
 *
 * New passwords are hashed with Argon2id. Legacy bcrypt hashes are verified
 * with bcrypt and automatically migrated to Argon2id on successful
 * authentication (see the login use case).
 *
 * Parameters chosen for this REST API's workload and deployment (Docker,
 * unconstrained container memory, authentication already rate-limited):
 * - memoryCost: 65536 KB (64 MiB) - OWASP guidance for Argon2id is 19 MiB at
 *   t=2; 64 MiB buys a substantial margin against GPU/ASIC brute force while
 *   remaining affordable for a request-scoped hash.
 * - timeCost: 3 iterations - exceeds the OWASP minimum of 2.
 * - parallelism: 4 - one lane per typical vCPU; the hash is produced once per
 *   login/registration on a multi-core container.
 * - hashLength: 32 bytes - 256-bit output.
 * - salt: 16 bytes - the Argon2 reference default, generated by the library
 *   from a CSPRNG on every hash.
 *
 * See docs/password-hashing.md for the benchmark backing these values.
 */
@Injectable()
export class Argon2Provider implements HashingProvider {
  private readonly memoryCost: number;
  private readonly timeCost: number;
  private readonly parallelism: number;
  private readonly hashLength: number;

  constructor(
    configService: ConfigService,
    private readonly logger: PinoLogger
  ) {
    this.memoryCost = configService.get<number>('ARGON2_MEMORY_COST') ?? 65536;
    this.timeCost = configService.get<number>('ARGON2_TIME_COST') ?? 3;
    this.parallelism = configService.get<number>('ARGON2_PARALLELISM') ?? 4;
    this.hashLength = configService.get<number>('ARGON2_HASH_LENGTH') ?? 32;

    this.logger.setContext(Argon2Provider.name);
  }

  /**
   * Hashes a password using Argon2id.
   *
   * Every password creation path (registration, password change, admin
   * invitations) goes through this method, so no new bcrypt hashes are ever
   * produced once this provider is wired in.
   */
  async hash(data: string | Buffer): Promise<string> {
    return argon2.hash(data, {
      type: argon2.argon2id,
      memoryCost: this.memoryCost,
      timeCost: this.timeCost,
      parallelism: this.parallelism,
      hashLength: this.hashLength
    });
  }

  /**
   * Verifies a password against a stored hash, dispatching on the hash format:
   * - `$argon2id$...` - Argon2id
   * - `$2a/$2b/$2x/$2y$...` - legacy bcrypt
   * - anything else - rejected as unsupported
   *
   * Malformed hashes are treated as a mismatch rather than an exception so a
   * corrupt row can never surface an internal hashing error to the client or a
   * 500 on the login path.
   */
  async compare(data: string | Buffer, encrypted: string): Promise<boolean> {
    if (this.isArgon2idHash(encrypted)) {
      return this.verifyArgon2id(data, encrypted);
    }

    if (this.isBcryptHash(encrypted)) {
      return this.verifyBcrypt(data, encrypted);
    }

    this.logger.warn(
      {
        event: 'password.verification.unsupported_format',
        hashPrefix: encrypted.substring(0, 10)
      },
      'Password hash has unsupported format'
    );

    return false;
  }

  /**
   * Reports whether a stored hash is legacy bcrypt and should be upgraded to
   * Argon2id on the next successful authentication.
   */
  needsMigration(encrypted: string): boolean {
    return this.isBcryptHash(encrypted);
  }

  private async verifyArgon2id(
    data: string | Buffer,
    encrypted: string
  ): Promise<boolean> {
    try {
      return await argon2.verify(encrypted, data);
    } catch {
      this.logger.warn(
        { event: 'password.verification.argon2_error' },
        'Failed to verify Argon2id hash'
      );
      return false;
    }
  }

  private async verifyBcrypt(
    data: string | Buffer,
    encrypted: string
  ): Promise<boolean> {
    try {
      return await bcrypt.compare(data, encrypted);
    } catch {
      this.logger.warn(
        { event: 'password.verification.bcrypt_error' },
        'Failed to verify legacy bcrypt hash'
      );
      return false;
    }
  }

  /**
   * Only Argon2id is accepted. Argon2i and Argon2d are not produced by this
   * system and are treated as unsupported rather than silently verified.
   */
  private isArgon2idHash(hash: string): boolean {
    return hash.startsWith('$argon2id$');
  }

  /**
   * bcrypt hashes start with "$2" plus a variant letter: `$2a$`, `$2b$`,
   * `$2x$` or `$2y$`.
   */
  private isBcryptHash(hash: string): boolean {
    return /^\$2[abxy]\$/.test(hash);
  }
}
