export enum SessionErrorCode {
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  SESSION_REUSE_DETECTED = 'SESSION_REUSE_DETECTED',
  REFRESH_RATE_LIMITED = 'REFRESH_RATE_LIMITED'
}
