export enum SessionErrorCode {
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  SESSION_REUSE_DETECTED = 'SESSION_REUSE_DETECTED',
  REFRESH_RATE_LIMITED = 'REFRESH_RATE_LIMITED',
  INVALID_CURSOR = 'INVALID_CURSOR',
  /** The current session was addressed by id instead of through `DELETE /`. */
  SESSION_IS_CURRENT = 'SESSION_IS_CURRENT'
}
