export enum AuthorizationErrorCode {
  OWNER_IMMUTABLE = 'OWNER_IMMUTABLE',
  OWNER_ALREADY_EXISTS = 'OWNER_ALREADY_EXISTS',
  OWNER_ROLE_NOT_ASSIGNABLE = 'OWNER_ROLE_NOT_ASSIGNABLE',
  NOT_AN_ADMINISTRATOR = 'NOT_AN_ADMINISTRATOR',
  ALREADY_AN_ADMINISTRATOR = 'ALREADY_AN_ADMINISTRATOR',
  SELF_MANAGEMENT_FORBIDDEN = 'SELF_MANAGEMENT_FORBIDDEN',
  PERMISSION_NOT_HELD = 'PERMISSION_NOT_HELD',
  ACCOUNT_NOT_ELIGIBLE = 'ACCOUNT_NOT_ELIGIBLE'
}
