export enum AssetErrorCode {
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  ASSET_INVALID_CURSOR = 'ASSET_INVALID_CURSOR',
  COINGECKO_API_ERROR = 'COINGECKO_API_ERROR',
  ASSET_SYNC_EMPTY_RESPONSE = 'ASSET_SYNC_EMPTY_RESPONSE'
}
