export enum AssetErrorCode {
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  ASSET_INVALID_CURSOR = 'ASSET_INVALID_CURSOR',
  ASSET_SYNC_EMPTY_RESPONSE = 'ASSET_SYNC_EMPTY_RESPONSE',
  MARKET_DATA_PROVIDER_RATE_LIMITED = 'MARKET_DATA_PROVIDER_RATE_LIMITED',
  MARKET_DATA_PROVIDER_TIMEOUT = 'MARKET_DATA_PROVIDER_TIMEOUT',
  MARKET_DATA_PROVIDER_UNAVAILABLE = 'MARKET_DATA_PROVIDER_UNAVAILABLE',
  MARKET_DATA_PROVIDER_BAD_REQUEST = 'MARKET_DATA_PROVIDER_BAD_REQUEST',
  MARKET_DATA_PROVIDER_INVALID_RESPONSE = 'MARKET_DATA_PROVIDER_INVALID_RESPONSE'
}
