export enum MarketOverviewErrorCode {
  MARKET_OVERVIEW_PROVIDER_RATE_LIMITED = 'MARKET_OVERVIEW_PROVIDER_RATE_LIMITED',
  MARKET_OVERVIEW_PROVIDER_TIMEOUT = 'MARKET_OVERVIEW_PROVIDER_TIMEOUT',
  MARKET_OVERVIEW_PROVIDER_UNAVAILABLE = 'MARKET_OVERVIEW_PROVIDER_UNAVAILABLE',
  MARKET_OVERVIEW_PROVIDER_BAD_REQUEST = 'MARKET_OVERVIEW_PROVIDER_BAD_REQUEST',
  MARKET_OVERVIEW_PROVIDER_INVALID_RESPONSE = 'MARKET_OVERVIEW_PROVIDER_INVALID_RESPONSE'
}
