export const MONGODB_CONNECTION_NAME = 'logs';

// Actor types for audit logs
export enum ActorType {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER',
  ANONYMOUS = 'ANONYMOUS'
}

// Audit actions
export enum AuditAction {
  // Authentication
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  RESEND_VERIFICATION_CODE = 'RESEND_VERIFICATION_CODE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',

  // Account
  ACCOUNT_UPDATE = 'ACCOUNT_UPDATE',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',

  // Portfolio
  PORTFOLIO_CREATED = 'PORTFOLIO_CREATED',
  PORTFOLIO_UPDATED = 'PORTFOLIO_UPDATED',
  PORTFOLIO_DELETED = 'PORTFOLIO_DELETED',

  // Transaction
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED = 'TRANSACTION_UPDATED',
  TRANSACTION_DELETED = 'TRANSACTION_DELETED',

  // Holding
  HOLDING_CREATED = 'HOLDING_CREATED',
  HOLDING_UPDATED = 'HOLDING_UPDATED',
  HOLDING_DELETED = 'HOLDING_DELETED',

  // Admin/Owner actions
  ADMIN_ACTION = 'ADMIN_ACTION',
  OWNER_ACTION = 'OWNER_ACTION'
}

// Resource types
export enum ResourceType {
  USER = 'USER',
  SESSION = 'SESSION',
  PORTFOLIO = 'PORTFOLIO',
  TRANSACTION = 'TRANSACTION',
  HOLDING = 'HOLDING',
  ASSET = 'ASSET',
  SYSTEM = 'SYSTEM'
}

// System log levels
export enum SystemLogLevel {
  DEBUG = 'DEBUG',
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL'
}

// System log events
export enum SystemLogEvent {
  // Application lifecycle
  APPLICATION_STARTED = 'APPLICATION_STARTED',
  APPLICATION_SHUTDOWN = 'APPLICATION_SHUTDOWN',
  APPLICATION_ERROR = 'APPLICATION_ERROR',

  // HTTP
  HTTP_REQUEST = 'HTTP_REQUEST',
  HTTP_RESPONSE = 'HTTP_RESPONSE',
  HTTP_ERROR = 'HTTP_ERROR',

  // Database
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_SLOW = 'DATABASE_QUERY_SLOW',

  // Queue/Jobs
  QUEUE_JOB_STARTED = 'QUEUE_JOB_STARTED',
  QUEUE_JOB_COMPLETED = 'QUEUE_JOB_COMPLETED',
  QUEUE_JOB_FAILED = 'QUEUE_JOB_FAILED',

  // External APIs
  EXTERNAL_API_CALL = 'EXTERNAL_API_CALL',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  EXTERNAL_API_TIMEOUT = 'EXTERNAL_API_TIMEOUT',

  // Asset synchronization
  ASSET_SYNC_STARTED = 'ASSET_SYNC_STARTED',
  ASSET_SYNC_COMPLETED = 'ASSET_SYNC_COMPLETED',
  ASSET_SYNC_FAILED = 'ASSET_SYNC_FAILED',

  // Performance
  PERFORMANCE_WARNING = 'PERFORMANCE_WARNING',
  MEMORY_WARNING = 'MEMORY_WARNING',

  // Security
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Other
  UNHANDLED_EXCEPTION = 'UNHANDLED_EXCEPTION',
  VALIDATION_ERROR = 'VALIDATION_ERROR'
}
